services:
  superset:
    image: apache/superset:latest
    user: root
    ports:
      - "8088:8088"
    env_file:
      - .env
    environment:
      - SUPERSET_BIND_ADDRESS=0.0.0.0
      - TMPDIR=/app/superset_home/tmp
    volumes:
      - ./data:/app/data
      - ./superset:/app/superset_home
      - ./scripts:/scripts
      - ./import:/import
      - ./tmp:/tmp
      - ./output:/output
      - ./.env:/scripts/dot.env
    command: ["/scripts/entrypoint.sh"]
    # >
    #   env bash -c "mkdir -p /tmp && chmod 1777 /tmp &&
    #           # wget and unzip only needed for duckdb workaround on M4 Mac
    #           echo 'HOST_UID: $HOST_UID' &&
    #           echo 'HOST_GID: $HOST_GID' &&
    #           chown -R $HOST_UID:$HOST_GID /app/data /app/superset_home /scripts /tmp /output &&
    #           apt-get update && apt-get install -y gettext-base && # wget unzip &&
    #           # Not working in orbstack on M4
    #           curl https://install.duckdb.org | sh &&
    #           export PATH=/root/.duckdb/cli/latest/:$PATH &&
    #           pip install duckdb duckdb-engine pillow &&
    #           # But this did work on ARM64:
    #           # wget https://github.com/duckdb/duckdb/releases/download/v1.2.2/duckdb_cli-linux-aarch64.zip &&
    #           # unzip duckdb_cli-linux-aarch64 -d /usr/local/bin &&
    #           # End of workaround
    #           cd /scripts &&
    #           NO_EXPORT=1 ./run.sh &&
    #           cd /app &&
    #           superset db upgrade &&
    #           superset fab create-admin --username christopher --firstname christopher --email chris@badmath.org --password admin &&
    #           superset init &&
    #           superset set_database_uri -d DuckDB-commodore -u duckdb:///app/data/commodore.duckdb &&
    #           gunicorn --bind 0.0.0.0:8088 'superset.app:create_app()' --workers 4 --timeout 120"

volumes:
  redis:



