-- Export random sample of comprehensive records

SELECT
    "E-Mail",
    "Instructor",
    "FirstName",
    "LastName",
    "School",
    "Department",
    "State",
    "Course Number",
    "Section",
    "Course Title",
    "Enrollments",
    "Period",
    "period_sortable",
    "instnm",
    "sector",
    "iclevel",
    "control",
    "instsize",
    "ISBN13",
    "Title",
    "Author",
    "Publisher",
    "Imprint",
    "Edition",
    "Published Year",
    "Format",
    "FormatType",
    "IPED ID",
    "SchoolYearType",
    "Dept Code",
    "Dept Description",
    "Course Level",
    "Course Subject",
    "Seats Taken",
    "Book Status",
    "efydetot_tot_22",
    "efyde_tot_22",
    "typeinst",
    "insttype",
    "is_opted_out",
    "opt_out_source"
FROM comprehensive_data
ORDER BY RANDOM()
LIMIT 10000
-- @PARTITION_BY: period_sortable
