#!/usr/bin/env python3
"""Safely push explicitly annotated Markdown files to existing Notion pages.

The default mode only validates files and reads every destination page.  Writes
require ``--apply``.  Applying is deliberately non-transactional: an edit that
has already succeeded is not rolled back if a later edit or verification fails.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
from urllib.parse import urlparse


UUID_RE = re.compile(r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
URL_UUID_RE = re.compile(r"(?i)(?<![0-9a-f])([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[0-9a-f]{32})(?![0-9a-f])")
H1_RE = re.compile(r"^#\s+(.+?)\s*$")
KEYS = {"notion-id", "notion-url", "notion-sync"}
ALLOWED_HOSTS = {"notion.so", "www.notion.so", "app.notion.com"}
SUBPROCESS_TIMEOUT_SECONDS = 60.0
MAX_REQUEST_BYTES = 500_000
MANIFEST_DEFAULT = Path("scripts/notion_sync_docs.txt")
STATE_DEFAULT = Path(".notion/prose-state.json")
GENERATED_OWNERSHIP_COMMENT = b"<!-- Generated by scripts/generate_data_dictionary.py; do not edit the body. -->"
DICTIONARY_NAME = "DATA-DICTIONARY.md"
MARKDOWN_LINK_RE = re.compile(r"(?<!!)\[([^\]\n]+)\]\(([^)\n]+)\)")
FENCE_RE = re.compile(r"^[ \t]{0,3}(`{3,}|~{3,})")
LIST_ITEM_RE = re.compile(r"^[ \t]*(?:[-+*]|\d+[.)])[ \t]+")
STRUCTURAL_RE = re.compile(r"^[ \t]{0,3}(?:#{1,6}[ \t]+|>|\||<|(?:={3,}|-{3,}|\*{3,}|_{3,})[ \t]*$|\[[^]]+\]:)")
ATX_HEADING_RE = re.compile(r"^([ \t]{0,3})(#{2,6})([ \t]+)")


class SyncError(Exception):
    pass


def reject_dictionary_inputs(names: list[str]) -> None:
    if any(
        Path(name).name == DICTIONARY_NAME
        or (
            Path(name).parent.name == "data-dictionary"
            and Path(name).parent.parent.name == "docs"
        )
        for name in names
    ):
        raise SyncError(
            "Data Dictionary pages are managed by sync_notion_dictionary.py and "
            "sync_notion_dictionary_downloads.py; do not publish it with sync_notion_docs.py"
        )


def canonical_uuid(value: str) -> str:
    if not UUID_RE.fullmatch(value):
        raise SyncError("notion-id must be a canonical UUID")
    return value.lower()


def parse_document(path: Path, repo_root: Path) -> tuple[str, str, bytes, str, str]:
    if ".." in path.parts:
        raise SyncError(f"path traversal is not allowed: {path}")
    lexical = path if path.is_absolute() else repo_root / path
    try:
        lexical_relative = lexical.relative_to(repo_root)
    except ValueError as exc:
        raise SyncError(f"file is outside the repository: {path}") from exc
    cursor = repo_root
    for component in lexical_relative.parts:
        cursor /= component
        if cursor.is_symlink():
            raise SyncError(f"symlinked sync input is not allowed: {path}")
    try:
        resolved = path.resolve(strict=True)
    except OSError as exc:
        raise SyncError(f"cannot resolve {path}: {exc}") from exc
    if not resolved.is_file() or resolved.suffix != ".md":
        raise SyncError(f"expected an existing .md file: {path}")
    try:
        resolved.relative_to(repo_root)
    except ValueError as exc:
        raise SyncError(f"file is outside the repository: {path}") from exc
    try:
        relative = resolved.relative_to(repo_root)
    except ValueError as exc:
        raise SyncError(f"file is outside the repository: {path}") from exc
    allowed = relative.parent == Path(".") or relative.parent == Path("docs/data-dictionary")
    if not allowed:
        raise SyncError(f"only top-level Markdown or direct docs/data-dictionary children may be synced: {path}")
    try:
        resolved.relative_to(repo_root / "comms")
    except ValueError:
        pass
    else:
        raise SyncError(f"comms/ files are not sync inputs: {path}")

    raw = resolved.read_bytes()
    lines = raw.splitlines(keepends=True)
    if not lines or lines[0].rstrip(b"\r\n") != b"---":
        raise SyncError(f"{path}: YAML frontmatter must be the first line")

    close = None
    for index in range(1, len(lines)):
        if lines[index].rstrip(b"\r\n") == b"---":
            close = index
            break
    if close is None:
        raise SyncError(f"{path}: YAML frontmatter has no closing ---")

    metadata: dict[str, str] = {}
    for line in lines[1:close]:
        if not line.endswith((b"\n", b"\r")):
            raise SyncError(f"{path}: malformed YAML line")
        text = line.decode("utf-8", "strict").rstrip("\r\n")
        match = re.fullmatch(r"([a-z][a-z0-9-]*): ([^\t\r\n]+)", text)
        if not match or match.group(1) not in KEYS:
            raise SyncError(f"{path}: frontmatter must contain only notion-id, notion-url, notion-sync scalar keys")
        key, value = match.groups()
        if key in metadata:
            raise SyncError(f"{path}: duplicate frontmatter key {key}")
        metadata[key] = value
    if set(metadata) != KEYS:
        raise SyncError(f"{path}: frontmatter requires notion-id, notion-url, and notion-sync")
    if metadata["notion-sync"] != "push":
        raise SyncError(f"{path}: notion-sync must be push")

    page_id = canonical_uuid(metadata["notion-id"])
    parsed = urlparse(metadata["notion-url"])
    if parsed.scheme != "https" or parsed.hostname not in ALLOWED_HOSTS or not parsed.path:
        raise SyncError(f"{path}: notion-url must be an HTTPS Notion page URL")
    candidates = URL_UUID_RE.findall(parsed.path)
    if len(candidates) != 1 or candidates[0].replace("-", "").lower() != page_id.replace("-", ""):
        raise SyncError(f"{path}: notion-url UUID does not match notion-id")

    body = b"".join(lines[close + 1 :])
    # Generated relation docs carry this exact ownership marker before their H1. Keep
    # ownership metadata local, but do not send the marker as a Notion content block.
    body_lines = body.splitlines(keepends=True)
    marker_index = 1 if body_lines and body_lines[0].strip() == b"" else 0
    if (
        marker_index < len(body_lines)
        and body_lines[marker_index].rstrip(b"\r\n")
        == GENERATED_OWNERSHIP_COMMENT
    ):
        body_lines = body_lines[marker_index + 1 :]
        if body_lines and body_lines[0].strip() == b"":
            body_lines = body_lines[1:]
        body = b"".join(body_lines)
    if not body.strip():
        raise SyncError(f"{path}: Markdown body is empty")
    if first_h1(body) is None:
        raise SyncError(f"{path}: Markdown body must contain a meaningful H1")
    return page_id, metadata["notion-url"], body, str(resolved), first_h1(body) or ""


def first_h1(markdown: bytes) -> str | None:
    for line in markdown.decode("utf-8", "replace").splitlines():
        if line.strip():
            match = H1_RE.fullmatch(line.strip())
            return match.group(1).strip() if match else None
    return None


def heading_sequence(markdown: bytes) -> list[tuple[int, str]]:
    headings = []
    fence: str | None = None
    for line in markdown.decode("utf-8", "replace").splitlines():
        fence_match = FENCE_RE.match(line)
        if fence_match:
            marker = fence_match.group(1)
            if fence is None:
                fence = marker
            elif marker[0] == fence[0] and len(marker) >= len(fence):
                fence = None
            continue
        if fence is not None or line.startswith(("    ", "\t")):
            continue
        match = re.fullmatch(r"[ \t]{0,3}(#{1,6})[ \t]+(.+?)[ \t]*", line)
        if match:
            headings.append((len(match.group(1)), match.group(2).strip()))
    return headings


def publication_markdown(markdown: bytes) -> bytes:
    """Prepare prose for Notion while leaving local Markdown unchanged."""
    text = markdown.decode("utf-8")
    output: list[str] = []
    fence: str | None = None

    def unlink_local(match: re.Match[str]) -> str:
        destination = match.group(2).strip()
        if destination.startswith("<") and ">" in destination:
            destination = destination[1 : destination.index(">")]
        else:
            destination = destination.split(maxsplit=1)[0]
        parsed = urlparse(destination)
        if parsed.scheme or parsed.netloc or destination.startswith(("#", "/")):
            return match.group(0)
        return match.group(1)

    for line in text.splitlines(keepends=True):
        match = FENCE_RE.match(line)
        if match:
            marker = match.group(1)
            if fence is None:
                fence = marker
            elif marker[0] == fence[0] and len(marker) >= len(fence):
                fence = None
            output.append(line)
        elif fence is None:
            line = ATX_HEADING_RE.sub(lambda match: f"{match.group(1)}{match.group(2)[1:]}{match.group(3)}", line)
            output.append(MARKDOWN_LINK_RE.sub(unlink_local, line))
        else:
            output.append(line)
    lines = "".join(output).splitlines()
    published: list[str] = []
    fence = None
    joinable = False
    for line in lines:
        match = FENCE_RE.match(line)
        if match:
            marker = match.group(1)
            if fence is None:
                fence = marker
            elif marker[0] == fence[0] and len(marker) >= len(fence):
                fence = None
            published.append(line)
            joinable = False
            continue
        if fence is not None or not line.strip():
            published.append(line)
            joinable = False
            continue

        is_list_item = bool(LIST_ITEM_RE.match(line))
        is_indented_code = line.startswith(("    ", "\t")) and not is_list_item
        is_structural = is_indented_code or bool(STRUCTURAL_RE.match(line))
        if joinable and not is_list_item and not is_structural:
            published[-1] = f"{published[-1].rstrip()} {line.lstrip()}"
        else:
            published.append(line)
        joinable = (is_list_item or not is_structural) and not (
            line.endswith("  ") or line.rstrip().endswith("\\")
        )

    suffix = "\n" if text.endswith(("\n", "\r")) else ""
    return ("\n".join(published) + suffix).encode("utf-8")


def inspect_page(raw: bytes, expected_id: str, path: str, require_body: bool) -> tuple[str, dict, str | None, list[tuple[int, str]], str | None]:
    try:
        payload = json.loads(raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise SyncError(f"{path}: ntn pages get returned invalid JSON") from exc
    if not isinstance(payload, dict) or not isinstance(payload.get("page"), dict):
        raise SyncError(f"{path}: pages get returned an unexpected JSON shape")
    page = payload["page"]
    actual_id = page.get("id")
    parent = page.get("parent")
    properties = page.get("properties")
    title_property = properties.get("title") if isinstance(properties, dict) else None
    title_parts = title_property.get("title") if isinstance(title_property, dict) else None
    title = "".join(item.get("plain_text", "") for item in title_parts or [] if isinstance(item, dict)).strip()
    markdown_value = payload.get("markdown")
    nested_id = None
    if isinstance(markdown_value, dict):
        nested_id = markdown_value.get("id")
        markdown = markdown_value.get("markdown")
        if markdown_value.get("truncated") is True or markdown_value.get("unknown_block_ids"):
            raise SyncError(f"{path}: pages get reported truncated or unknown blocks")
    else:
        markdown = markdown_value
    def has_unknown_blocks(value: object) -> bool:
        if isinstance(value, dict):
            if value.get("unknown_block_ids"):
                return True
            return any(has_unknown_blocks(item) for item in value.values())
        if isinstance(value, list):
            return any(has_unknown_blocks(item) for item in value)
        return False
    if has_unknown_blocks(payload):
        raise SyncError(f"{path}: pages get reported truncated or unknown blocks")
    if nested_id is not None and (not isinstance(nested_id, str) or canonical_uuid(nested_id) != expected_id):
        raise SyncError(f"{path}: page markdown returned an unexpected page ID")
    if not isinstance(actual_id, str) or canonical_uuid(actual_id) != expected_id:
        raise SyncError(f"{path}: pages get returned an unexpected page ID")
    if not title or not isinstance(parent, dict) or not parent:
        raise SyncError(f"{path}: pages get did not return a meaningful title and full parent")
    if markdown is not None and not isinstance(markdown, str):
        raise SyncError(f"{path}: pages get returned invalid markdown")
    if require_body and (not markdown or not markdown.strip()):
        raise SyncError(f"{path}: pages get returned an empty body after edit")
    return title, parent, first_h1(markdown.encode()) if markdown else None, heading_sequence(markdown.encode()) if markdown else [], markdown


def run_get(ntn: str, page_id: str, path: str, require_body: bool) -> tuple[str, dict, str | None, list[tuple[int, str]], str | None]:
    env = os.environ.copy()
    env["NOTION_KEYRING"] = "0"
    try:
        result = subprocess.run([ntn, "pages", "get", page_id, "--json"], capture_output=True, env=env, timeout=SUBPROCESS_TIMEOUT_SECONDS)
    except subprocess.TimeoutExpired as exc:
        raise SyncError(f"{path}: pages get timed out after {SUBPROCESS_TIMEOUT_SECONDS:g}s") from exc
    if result.returncode:
        raise SyncError(f"{path}: pages get failed (exit {result.returncode})")
    return inspect_page(result.stdout, page_id, path, require_body)


def _api_error(result: subprocess.CompletedProcess[bytes], path: str, operation: str) -> SyncError:
    stderr = result.stderr.decode("utf-8", "replace").strip()
    stdout = result.stdout.decode("utf-8", "replace").strip()
    detail = stderr or stdout or "no error details"
    return SyncError(f"{path}: Notion API {operation} failed (exit {result.returncode}): {detail}")


def load_manifest(manifest: Path, repo_root: Path) -> list[str]:
    if manifest.is_absolute() or ".." in manifest.parts:
        raise SyncError(f"manifest must be a repository-relative path: {manifest}")
    manifest_path = repo_root / manifest
    if manifest_path.is_symlink():
        raise SyncError(f"symlinked manifest is not allowed: {manifest}")
    try:
        manifest_path = manifest_path.resolve(strict=True)
    except OSError as exc:
        raise SyncError(f"cannot read manifest {manifest}: {exc}") from exc
    if manifest_path.parent != repo_root / "scripts" or manifest_path.name != "notion_sync_docs.txt":
        raise SyncError(f"manifest must be scripts/notion_sync_docs.txt: {manifest}")
    lines = manifest_path.read_text(encoding="utf-8").splitlines()
    names = [line.strip() for line in lines if line.strip() and not line.lstrip().startswith("#")]
    if not names:
        raise SyncError(f"manifest is empty: {manifest}")
    if len(names) != len(set(names)):
        raise SyncError(f"manifest contains duplicate paths: {manifest}")
    if any(Path(name).is_absolute() or ".." in Path(name).parts for name in names):
        raise SyncError(f"manifest paths must be repository-relative without traversal: {manifest}")
    return names


def run_edit(ntn: str, page_id: str, body: bytes, path: str) -> str:
    request = json.dumps({"allow_async": False, "type": "replace_content", "replace_content": {"new_str": body.decode("utf-8")}}, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    if len(request) >= MAX_REQUEST_BYTES:
        raise SyncError(f"{path}: replacement request is {len(request)} bytes; maximum is {MAX_REQUEST_BYTES - 1}")
    env = os.environ.copy()
    env["NOTION_KEYRING"] = "0"
    try:
        result = subprocess.run([ntn, "api", f"/v1/pages/{page_id}/markdown", "--method", "PATCH", "--data", "@-"], input=request, capture_output=True, env=env, timeout=SUBPROCESS_TIMEOUT_SECONDS)
    except subprocess.TimeoutExpired as exc:
        raise SyncError(f"{path}: Notion API submit timed out after {SUBPROCESS_TIMEOUT_SECONDS:g}s") from exc
    if result.returncode:
        raise _api_error(result, path, "submit")
    try:
        payload = json.loads(result.stdout)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise SyncError(f"{path}: Notion API submit returned invalid JSON") from exc
    if not isinstance(payload, dict) or payload.get("object") != "page_markdown" or payload.get("id") != page_id or not isinstance(payload.get("markdown"), str) or payload.get("truncated") is not False or payload.get("unknown_block_ids") != []:
        raise SyncError(f"{path}: Notion API submit returned an invalid page_markdown response")
    return payload["markdown"]


def normalize_markdown(value: str | bytes | None) -> str | None:
    """Normalize only transport-level differences in Notion Markdown."""
    if value is None:
        return None
    if isinstance(value, bytes):
        value = value.decode("utf-8")
    value = value.replace("\r\n", "\n").replace("\r", "\n")
    return value.strip("\n")


def markdown_digest(value: str | bytes) -> str:
    if isinstance(value, str):
        value = value.encode("utf-8")
    return hashlib.sha256(value).hexdigest()


def load_state(path: Path) -> dict[str, dict[str, str]]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise SyncError(f"cannot read prose sync state {path}: {exc}") from exc
    pages = payload.get("pages") if isinstance(payload, dict) else None
    if not isinstance(pages, dict):
        raise SyncError(f"prose sync state has an unexpected shape: {path}")
    for page_id, entry in pages.items():
        if (
            not isinstance(entry, dict)
            or not isinstance(entry.get("markdown"), str)
            or ("desired_sha256" in entry and not isinstance(entry["desired_sha256"], str))
            or ("pending_sha256" in entry and not isinstance(entry["pending_sha256"], str))
        ):
            raise SyncError(f"prose sync state has an invalid page entry: {page_id}")
    return pages


def save_state(path: Path, pages: dict[str, dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text(
            json.dumps({"version": 1, "pages": pages}, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        os.replace(temporary, path)
    except OSError as exc:
        temporary.unlink(missing_ok=True)
        raise SyncError(f"cannot write prose sync state {path}: {exc}") from exc


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Check or push annotated Notion Markdown pages. --apply writes; apply is non-transactional if a later edit fails."
    )
    parser.add_argument("--apply", action="store_true", help="perform edits after all read-only preflights succeed")
    parser.add_argument(
        "--initialize-state",
        action="store_true",
        help="adopt current content as the baseline only where it already matches local content; never edit Notion",
    )
    parser.add_argument("--state-file", type=Path, default=STATE_DEFAULT, help=argparse.SUPPRESS)
    parser.add_argument("--ntn", default="ntn", help="ntn executable path (default: ntn)")
    parser.add_argument("--manifest", type=Path, help="read an explicit newline-delimited file list")
    parser.add_argument("files", nargs="*", help="explicit repository .md files")
    args = parser.parse_args(argv)
    if args.manifest and args.files:
        parser.error("--manifest cannot be combined with file arguments")
    if args.apply and args.initialize_state:
        parser.error("--apply cannot be combined with --initialize-state")
    if not args.manifest and not args.files:
        parser.error("provide file arguments or --manifest")
    try:
        reject_dictionary_inputs(args.files)
    except SyncError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    ntn = args.ntn
    if not os.path.dirname(ntn):
        from shutil import which
        ntn = which(ntn) or ""
    if not ntn or not os.access(ntn, os.X_OK):
        print("error: ntn executable not found or not executable", file=sys.stderr)
        return 2
    repo_root = Path(__file__).resolve().parent.parent
    state_path = args.state_file if args.state_file.is_absolute() else repo_root / args.state_file
    documents = []
    try:
        names = args.files
        if args.manifest:
            names = load_manifest(args.manifest, repo_root)
        reject_dictionary_inputs(names)
        for name in names:
            page_id, url, body, path, h1 = parse_document(Path(name), repo_root)
            documents.append((page_id, url, body, path, h1))
        paths = [item[3] for item in documents]
        ids = [item[0] for item in documents]
        if len(paths) != len(set(paths)):
            raise SyncError("duplicate local file arguments")
        if len(ids) != len(set(ids)):
            raise SyncError("duplicate notion-id arguments")
        state = load_state(state_path)
        snapshots = []
        conflicts: list[str] = []
        for page_id, _url, body, path, _local_h1 in documents:
            title, parent, remote_h1, remote_headings, remote_markdown = run_get(ntn, page_id, path, False)
            snapshots.append((title, parent, remote_h1, remote_headings, remote_markdown))
            desired = normalize_markdown(publication_markdown(body))
            desired_sha256 = markdown_digest(desired or "")
            remote = normalize_markdown(remote_markdown)
            entry = state.get(page_id)
            if entry is None:
                if args.initialize_state and remote == desired:
                    state[page_id] = {"path": str(Path(path).relative_to(repo_root)), "markdown": remote or "", "desired_sha256": desired_sha256}
                    print(f"INITIALIZE {path} -> {page_id}")
                else:
                    conflicts.append(f"{path}: no saved baseline; run --initialize-state after confirming remote content matches local")
                continue
            baseline = normalize_markdown(entry["markdown"])
            if remote != baseline and remote != desired:
                conflicts.append(f"{path}: remote content changed since the saved baseline")
            elif entry.get("pending_sha256") == desired_sha256 and remote == baseline:
                print(f"RECOVER {path} -> {page_id} (verify prior edit)")
            elif entry.get("desired_sha256") == desired_sha256 or desired == remote:
                print(f"UNCHANGED {path} -> {page_id}")
            else:
                print(f"CHANGE {path} -> {page_id} (body {len(body)} bytes)")
        if args.initialize_state:
            if conflicts:
                raise SyncError("prose sync conflicts:\n  " + "\n  ".join(conflicts))
            save_state(state_path, state)
            return 0
        if conflicts:
            raise SyncError("prose sync conflicts:\n  " + "\n  ".join(conflicts))
        if not args.apply:
            return 0
        for (page_id, _url, body, path, _local_h1), (title, parent, _remote_h1, _remote_headings, _remote_markdown) in zip(documents, snapshots):
            body = publication_markdown(body)
            desired = normalize_markdown(body)
            desired_sha256 = markdown_digest(desired or "")
            baseline = normalize_markdown(state[page_id]["markdown"])
            if state[page_id].get("pending_sha256") == desired_sha256 and normalize_markdown(_remote_markdown) == baseline:
                if _remote_h1 != (first_h1(body) or "") or _remote_headings != heading_sequence(body):
                    raise SyncError(f"{path}: prior edit readback has unexpected headings")
                state[page_id] = {"path": str(Path(path).relative_to(repo_root)), "markdown": baseline or "", "desired_sha256": desired_sha256}
                save_state(state_path, state)
                print(f"APPLY {path} -> {page_id} recovered and verified")
                continue
            if state[page_id].get("desired_sha256") == desired_sha256 or desired == normalize_markdown(_remote_markdown):
                if state[page_id].get("desired_sha256") != desired_sha256:
                    state[page_id] = {"path": str(Path(path).relative_to(repo_root)), "markdown": normalize_markdown(_remote_markdown) or "", "desired_sha256": desired_sha256}
                    save_state(state_path, state)
                continue
            local_h1 = first_h1(body) or ""
            # Close the preflight-to-write window. A remote edit at any point before
            # this read aborts the page without issuing a mutation.
            current_title, current_parent, _h1, _headings, current_markdown = run_get(ntn, page_id, path, False)
            if current_title != title or current_parent != parent or normalize_markdown(current_markdown) != baseline:
                raise SyncError(f"{path}: remote content changed immediately before edit")
            submitted_markdown = run_edit(ntn, page_id, body, path)
            # Persist the acknowledged canonical response before readback. If the
            # process stops here, the next --apply verifies this pending baseline
            # and does not repeat the mutation.
            state[page_id] = {"path": str(Path(path).relative_to(repo_root)), "markdown": normalize_markdown(submitted_markdown) or "", "pending_sha256": desired_sha256}
            save_state(state_path, state)
            new_title, new_parent, new_h1, new_headings, new_markdown = run_get(ntn, page_id, path, True)
            if new_title != title or new_parent != parent or new_h1 != local_h1 or new_headings != heading_sequence(body) or normalize_markdown(submitted_markdown) != normalize_markdown(new_markdown):
                raise SyncError(f"{path}: title, parent, or H1 changed during edit")
            state[page_id] = {"path": str(Path(path).relative_to(repo_root)), "markdown": normalize_markdown(new_markdown) or "", "desired_sha256": desired_sha256}
            save_state(state_path, state)
            print(f"APPLY {path} -> {page_id} verified")
    except SyncError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
